### PR TITLE
[WiP] Metrics collector

### PR DESCRIPTION
**Pull request by SonicDMG**
This pull request adds the metrics collector containers and configuration needed to enable metrics with prometheus and grafana.

### CODE REVIEW

**Comment by HadesArchitect** [comment]
Hey, this one brings changes to the main docker-compose.yml **I would avoid**.

**Comment by SonicDMG** [comment]
> Hey, this one brings changes to the main docker-compose.yml **I would avoid**.

@HadesArchitect, I assume you are referring to the prometheus and grafana sections.  Do you have a suggestion on how to handle?  Should we simply comment them out or something else?  I would normally create a separate yaml file, but I don't think that works when exporting for k8's.

**Comment by SonicDMG** [comment]
As I think about it more the answer here will also have impact for other changes coming in the future as this version replaces the current KillrVideo setup, namely, things like various security settings, use of persistent volumes, etc...  These are options available in the current KillrVideo project via multiple docker-compose*.yaml files.  We'll eventually need to account for these types of config needs.

**Comment by HadesArchitect** [comment]
> I assume you are referring to the prometheus and grafana sections. Do you have a suggestion on how to handle?

Exactly. All the additional features should not be included into the main docker-compose file as long as we want to keep it simple and obvious. The main docker-compose.yaml should stay as simple and short as possible. There are a few ways how to handle it but I'm afraid we need an additional meeting about that. I have a couple of ideas of course.

>  the answer here will also have impact for other changes coming in the future

That's the point. We have to agree upon the general approach. Today it's the metrics feature, tomorrow OpsCenter etc.

> I would normally create a separate yaml file, but I don't think that works when exporting for k8's.

Kompose supports as much files as you need: `kompose -f docker-compose.yml -f docker-guestbook.yml convert`

Another point that we may think of 'detaching' k8s part from docker-compose part.

**Comment by HadesArchitect** [comment]
Hey guys @SonicDMG @jeffreyscarpenter! As promised, did a little review. It works and looks good! =) 

image

[Moved my suggestions to a dedicated review comment]

I feel like we need a meeting about that. What do you think?

**Review by HadesArchitect — CHANGES_REQUESTED** [review]
1. The main docker-compose.yaml should be not touched to keep it simple and obvious.
2. The PR creates a lot of new folders spreading the changes over the repo. Shouldn't we better keep them all in a single folder like 'metrics-demo'? Then it makes sense to have a 'merged' docker-compose there as well.
3. The Main readme file should be extended to have info about the metrics demo
4. Haven't found any usage of *.png files from the docs folder... Maybe missed anything?
5. demo/readme link leads to a wrong repo? "Clone or download this repo" https://github.com/datastax/dse-metric-reporter-dashboards/archive/master.zip ?
6. Grafana's port 3000 makes a port collision with KV port 3000 if it's running.
7. Exactly this demo seems to be not related to the killrvideo. If it's indeed, shouldn't it be in a separate repo maybe? If it relates to the KV, should it maybe use DSE server from the KV so we have more related metrics?

**Pull request closed without merging**
